### ISSUE TITLE
Request more detailed instructions 

### ISSUE THREAD

**Issue by Rich1975** [Gordon999/Pi_OLED-MP3-Player#1]
Hi, for some of us new to the Raspberry Pi (I know it been out there for a long time), it would be nice to have some more instructions to follow your project. I have managed to do part of the project using other projects details and now stuck at setting the audio output, even so another problem being a blank display ..no lights at all, hope to research and solve these problems. Thanks for the design

**Comment by Gordon999** [comment]
Regarding the audio, l use the RaspiOS GUI ( Bullseye not Bookworm) and right click on the loudspeaker icon and choose the required output.

With the blank screen have you checked the wiring ? Note numbers in ( ) are physical pin numbers.

Followed all the instructions for installs ?

Installed the adafruit driver ?

Do you get any errors when running the code ?

**Comment by Rich1975** [comment]
Thank you for your reply/suggestions,
as to the audio, yes, I have made sure that the 3.5mm audio jack is selected and after loadiing some songs into the Music folder I was able to click on it and play the audio file through the audio jack with headphones.

The blank screen problem, well i researched on the internet and found https://www.raspberrypi-spy.co.uk/2018/04/i2c-oled-display-module-with-raspberry-pi/#Finding%20The%20OLED%20Display%20Module%E2%80%99S%20Address
which I followed and proved that the display works.
Yes I have installed the drivers as per your instructions, which brings me to running the code.... I am not sure how that is done, as a matter of fact in your instructions you state "to run at boot add /usr/bin/python3 /home/USERNAME/Pi_OLED_MP3_Player.py to /etc/xdg/lxsession/LXDE-pi/autostart" BUT, I cant save the autostart file, it must be write protected or I dont have the permission to do so (some message about the file being truncated).
Any further assistance would be greatly appreciated.
Thanks again.

**Comment by Gordon999** [comment]
sudo nano /etc/xdg/lxsession/LXDE-pi/autostart

Add..

@sudo /usr/bin/python3 /home/USERNAME/Pi_OLED_MP3_Player.py

( change USERNAME to your login name)

Then press ctrl & X, and then Y and enter.

reboot

**Comment by Gordon999** [comment]
Assumed fixed

**Comment by Rich1975** [comment]
Hi, 
Sadly no, 
Using Raspberry pi 3 Model A+ (2022), OS ver Bullseye 32 bit, and .96" OLED display.
I still get no display at all and no sound at all.
I have left the wiring intact and loaded other software to test the display and it works.
I have copied MP3's to the Music folder and am able to double click and play the music which tells me the sound is available at the 3.5mm plug.

Failing this I tried the "5B_LCD_MP3_Player" using the same ver OS on a 256gb micro sd card, a 2004 LCD display and changed the appropriate settings for the display in the text of "5B_LCD_MP3_Player", here too no info is displayed, (the LCD backlight is on and am able to adjust the contrast), and no sound..
The suggestion of using sudo nano to add the @ sudo /usr/bin/python/home/rich/file name of player.py to autostart didn't help.
I'm at a loss, but forgive me I'm a 78 yr old man trying this for the first time. Im, not giving up yet, I'll paper print out of the program and try to learn the logic behind it.
Cheers

**Comment by Gordon999** [comment]
What is a 2004 LCD display?

Is it a 16x2  LCD as used here https://github.com/Gordon999/Pi_5B_LCD_MP3_Player ?

I have tried a new SD card, 32 bit latest bullseye OS, 0.96 oled and followed the instructions and all works fine. So l am a bit at a loss at the moment why you can't get it to work.

Do you see any errors ?

**Comment by Rich1975** [comment]
Hi,
Oh! thats a 4 line display, 16x4.
No, I dont see any errors.
If I remember right... to start the program from the desktop it click on the Raspberry pi icon, scroll down to run the enter the name of the player/program you want and then enter to start Iit, am I right? then too no error messages

**Comment by Gordon999** [comment]
I just open a terminal and type

python3 Pi_OLED_MP3_Player.py

Are you putting the python script in /home/USERNAME?

where USERNAME is what you login as

**Comment by Rich1975** [comment]
Hi, this is the message I get when I type in   python3 Pi_OLED_MP3_Player.py   in open terminal
rich@raspberrypi:~ $ python3 Pi_OLED_MP3_Player.py
Traceback (most recent call last):
  File "/home/rich/Pi_OLED_MP3_Player.py", line 114, in <module>
    disp.begin()
  File "/usr/local/lib/python3.9/dist-packages/Adafruit_SSD1306-1.6.2-py3.9.egg/Adafruit_SSD1306/SSD1306.py", line 148, in begin
  File "/usr/local/lib/python3.9/dist-packages/Adafruit_SSD1306-1.6.2-py3.9.egg/Adafruit_SSD1306/SSD1306.py", line 292, in _initialize
  File "/usr/local/lib/python3.9/dist-packages/Adafruit_SSD1306-1.6.2-py3.9.egg/Adafruit_SSD1306/SSD1306.py", line 129, in command
  File "/usr/local/lib/python3.9/dist-packages/Adafruit_GPIO-1.0.4-py3.9.egg/Adafruit_GPIO/I2C.py", line 116, in write8
  File "/usr/local/lib/python3.9/dist-packages/Adafruit_PureIO-1.1.11-py3.9.egg/Adafruit_PureIO/smbus.py", line 316, in write_byte_data
    self._device.write(data)
OSError: [Errno 121] Remote I/O error

Hope this helps

**Comment by Gordon999** [comment]
Maybe a wiring issue, can you upload some photos of pi and oled connections.

I assume you are using the oled, my original code and have i2c enabled.

**Comment by Rich1975** [comment]
![IMG_20240421_085608046_HDR](https://github.com/Gordon999/Pi_OLED-MP3-Player/assets/65562141/f6c91c13-1c92-44b5-b1e5-e3a3a1e85e12)
![IMG_20240421_085715114_HDR](https://github.com/Gordon999/Pi_OLED-MP3-Player/assets/65562141/78c80a06-0e5a-4414-bd02-0132c3bfb71f)
Hi, hope this helps.

**Comment by Rich1975** [comment]
![IMG_20240421_085715114_HDR](https://github.com/Gordon999/Pi_OLED-MP3-Player/assets/65562141/a7365da5-74b1-4928-8548-bf966f351e54)
![IMG_20240421_085608046_HDR](https://github.com/Gordon999/Pi_OLED-MP3-Player/assets/65562141/f6c91c13-1c92-44b5-b1e5-e3a3a1e85e12)

**Comment by Gordon999** [comment]
The orange and yellow wires are the wrong way around on the pi, swap them over.

**Comment by Rich1975** [comment]
![IMG_20240421_123545625_HDR](https://github.com/Gordon999/Pi_OLED-MP3-Player/assets/65562141/a7b47450-d90e-40eb-9401-a8c69ac68ffc)
![IMG_20240421_123842481_HDR](https://github.com/Gordon999/Pi_OLED-MP3-Player/assets/65562141/9e8ec79f-983e-4e65-9652-7a0faa54394d)

![IMG_20240421_123906222_HDR](https://github.com/Gordon999/Pi_OLED-MP3-Player/assets/65562141/fea4d0d4-f8d0-498f-af04-f1fa6dcbe2f4)
![IMG_20240421_123906222_HDR](https://github.com/Gordon999/Pi_OLED-MP3-Player/assets/65562141/a301b884-54c5-4d5d-b841-7cb250297b90)

![IMG_20240421_125556436_HDR](https://github.com/Gordon999/Pi_OLED-MP3-Player/assets/65562141/5a9ea44a-ec66-4697-8cdf-2820eff33e3e)
Thank you, you must have the patience of Job!

**Comment by Gordon999** [comment]
Any errors still shown ?

**Comment by Rich1975** [comment]
[output2.txt](https://github.com/Gordon999/Pi_OLED-MP3-Player/files/15055004/output2.txt)

![IMG_20240421_123842481_HDR](https://github.com/Gordon999/Pi_OLED-MP3-Player/assets/65562141/ef33490d-6057-49fa-b8ff-e0b1d5162354)

**Comment by Gordon999** [comment]
I would recommend building a new sd card with 32bit RaspiOS based on Bullseye, and trying the installation again.

**Comment by Rich1975** [comment]
Hi, yes, I'm working on it. Will let you know how it goes. Thanks for your help and patience

**Comment by Gordon999** [comment]
![IMG_20240423_105645](https://github.com/Gordon999/Pi_OLED-MP3-Player/assets/15231212/bc5b169b-20f4-4a31-a23d-86396210cc47)

**Comment by Gordon999** [comment]
![IMG_20240423_112147](https://github.com/Gordon999/Pi_OLED-MP3-Player/assets/15231212/87d579c4-6556-45b1-880e-37b8b6d9e102)

**Comment by Rich1975** [comment]
Success! Thanks ever so much! 
Next.....
1) Add INNO-MAKER/AMP-Hat-for Raspberry-Pi (From Amazon)
2) Add more Radio stations (Los Angeles area)
3) If possible Use a larger display, I have ...
     1) 2.8" SPI TFT Module driver iLi9341 touch
     2) 3.2" SPI TFT Module driver iLi9341 touch
     3) LCD 2004 -20X4 Display
     4) .96 OLED Display that I'm using (small and hard to read)
![IMG_20240423_081510652_HDR](https://github.com/Gordon999/Pi_OLED-MP3-Player/assets/65562141/5c6c3a4c-4da1-4888-ac18-55aa669f0432)

Any help would be appreciated!

**Comment by Gordon999** [comment]
You could try the tfts with this https://github.com/Gordon999/Pi-MP3_Player

Set cutdown = 1 in the code

This can use a 4x20 lcd https://github.com/Gordon999/Pi_5B_LCD_MP3_Player/blob/main/5B_LCD_MP3_Player.py
Set lcd_lines   = 4 in  code

**Comment by Gordon999** [comment]
Assumed fixed

**Comment by Rich1975** [comment]
Yes!
Hi, thanks for all your support, 
Objective 1) to add audio also was successful.
Now on to the others.
Thanks again, its rare to see Creators/Makers/Enthusiasts, support amateurs like me when we ask questions
Will surely try making the tfts  Pi-MP3_Player Set cutdown=1 in the code
Have a Great day!

**Comment by Gordon999** [comment]
Thanks.
I could make a simple player similar to this oled player but using a tft and pygame if you struggle with MP3_Player.
Which tft do you have ?

**Comment by Rich1975** [comment]
Hi, You are very kind, I do appreciate the offer,
As you can see from the pics I have programed the microSD card for MP3_Player cutdown =1 (line 39 of your code) and everything is OK, though I wish there was room to include the album cover pic on the display (too small?)... I am not about to buy any more displays, would like to use what I have, 2.8"TFT SPI 240x320 and 3.2" TFT SPI 240x320 and a few 20 column x 4 line  (20x4) LCD displays with i2C interface. So, looks like I'm on my way to figuring out the wiring for the cutdown =1 MP3_player and then a cabinet to complete the project. 
Cheers!

![IMG_20240426_102925383_HDR](https://github.com/Gordon999/Pi_OLED-MP3-Player/assets/65562141/61a1599b-9313-446c-9220-832325ceb57e)

![IMG_20240426_104048518_HDR](https://github.com/Gordon999/Pi_OLED-MP3-Player/assets/65562141/a71f1364-2c96-41d5-b210-5fb998992259)

**Comment by Gordon999** [comment]
Glad you got it working.
Yes the display a bit too small for the album pic, may take a look what could be done.

**Comment by Gordon999** [comment]
please try https://github.com/Gordon999/Pi-MP3_Player  latest version

Album cover jpgs must be in album directories, where the tracks are. They don't need to be large images.

Please open any issues under https://github.com/Gordon999/Pi-MP3_Player/issues
